server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost}:3306/paymentdb
    username: root
    password: vipul
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296