server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:localhost}:3306/orderdb
    username: root
    password: vipul
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-24631635.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            clientId: 0oaie4om2pw7tZDKs5d7
            clientSecret: XPktFNEkraOZvIxZmg0LKWBcq70dRi635TsyqkpK0URxS4Vocmve6XxnpvJGm_nc
        provider:
          okta:
            issuerUri: https://dev-24631635.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}